// Token mappings for the Power UI design system
// These mappings are fixed to ensure consistency across all themes
export const TOKEN_MAPPINGS = {
  light: {
    // Text tokens
    'text-primary': 'neutral-900',
    'text-primary_on-brand': 'base-white',
    'text-secondary': 'neutral-700',
    'text-secondary_hover': 'neutral-800',
    'text-secondary_on-brand': 'brand-200',
    'text-tertiary': 'neutral-600',
    'text-tertiary_hover': 'neutral-700',
    'text-tertiary_on-brand': 'brand-200',
    'text-quaternary': 'neutral-500',
    'text-quaternary_on-brand': 'brand-300',
    'text-white': 'base-white',
    'text-disabled': 'neutral-500',
    'text-placeholder': 'neutral-500',
    'text-placeholder_subtle': 'neutral-300',
    'text-brand-primary': 'brand-900',
    'text-brand-secondary': 'brand-700',
    'text-brand-tertiary': 'brand-600',
    'text-brand-tertiary_alt': 'brand-600',
    'text-error-primary': 'error-600',
    'text-warning-primary': 'warning-600',
    'text-success-primary': 'success-600',

    // Border tokens
    'border-primary': 'neutral-300',
    'border-secondary': 'neutral-200',
    'border-tertiary': 'neutral-100',
    'border-disabled': 'neutral-300',
    'border-disabled_subtle': 'neutral-200',
    'border-brand': 'brand-300',
    'border-brand-solid': 'brand-600',
    'border-brand-solid_alt': 'brand-600',
    'border-error': 'error-300',
    'border-error-solid': 'error-600',

    // Button tokens
    'button-secondary-fg': 'neutral-700',
    'button-secondary-fg_hover': 'neutral-800',
    'button-secondary-bg': 'base-white',
    'button-secondary-bg_hover': 'neutral-50',
    'button-secondary-bg_press': 'neutral-100',
    'button-secondary-border': 'neutral-300',
    'button-secondary-border_hover': 'neutral-300',

    // Foreground tokens
    'fg-primary': 'neutral-900',
    'fg-secondary': 'neutral-700',
    'fg-secondary_hover': 'neutral-800',
    'fg-tertiary': 'neutral-600',
    'fg-tertiary_hover': 'neutral-700',
    'fg-quaternary': 'neutral-500',
    'fg-quaternary_hover': 'neutral-600',
    'fg-quinary': 'neutral-400',
    'fg-quinary_hover': 'neutral-500',
    'fg-senary': 'neutral-300',
    'fg-white': 'base-white',
    'fg-disabled': 'neutral-400',
    'fg-disabled_subtle': 'neutral-300',
    'fg-brand-primary': 'brand-600',
    'fg-brand-primary_alt': 'brand-600',
    'fg-brand-secondary': 'brand-500',
    'fg-error-primary': 'error-600',
    'fg-error-secondary': 'error-500',
    'fg-warning-primary': 'warning-600',
    'fg-warning-secondary': 'warning-500',
    'fg-success-primary': 'success-600',
    'fg-success-secondary': 'success-500',

    // Background tokens
    'bg-primary': 'base-white',
    'bg-primary_alt': 'base-white',
    'bg-primary_hover': 'neutral-50',
    'bg-primary_press': 'neutral-100',
    'bg-secondary': 'neutral-50',
    'bg-secondary_alt': 'neutral-50',
    'bg-secondary_hover': 'neutral-100',
    'bg-secondary_press': 'neutral-200',
    'bg-secondary_subtle': 'neutral-25',
    'bg-secondary_solid': 'neutral-200',
    'bg-tertiary': 'neutral-100',
    'bg-quaternary': 'neutral-200',
    'bg-active': 'neutral-50',
    'bg-disabled': 'neutral-100',
    'bg-disabled_subtle': 'neutral-50',
    'bg-overlay': 'neutral-950',
    'bg-brand-primary': 'brand-50',
    'bg-brand-primary_alt': 'brand-50',
    'bg-brand-secondary': 'brand-100',
    'bg-brand-solid': 'brand-600',
    'bg-brand-solid_hover': 'brand-700',
    'bg-brand-solid_press': 'brand-800',
    'bg-brand-section': 'brand-800',
    'bg-brand-section_subtle': 'brand-700',
    'bg-error-primary': 'error-50',
    'bg-error-secondary': 'error-100',
    'bg-error-solid': 'error-600',
    'bg-warning-primary': 'warning-50',
    'bg-warning-secondary': 'warning-100',
    'bg-warning-solid': 'warning-600',
    'bg-success-primary': 'success-50',
    'bg-success-secondary': 'success-100',
    'bg-success-solid': 'success-600'
  },
  dark: {
    // Text tokens
    'text-primary': 'neutral-50',
    'text-primary_on-brand': 'base-white',
    'text-secondary': 'neutral-300',
    'text-secondary_hover': 'neutral-200',
    'text-secondary_on-brand': 'brand-200',
    'text-tertiary': 'neutral-400',
    'text-tertiary_hover': 'neutral-300',
    'text-tertiary_on-brand': 'brand-200',
    'text-quaternary': 'neutral-400',
    'text-quaternary_on-brand': 'brand-300',
    'text-white': 'base-white',
    'text-disabled': 'neutral-500',
    'text-placeholder': 'neutral-400',
    'text-placeholder_subtle': 'neutral-600',
    'text-brand-primary': 'brand-300',
    'text-brand-secondary': 'brand-200',
    'text-brand-tertiary': 'brand-400',
    'text-brand-tertiary_alt': 'brand-400',
    'text-error-primary': 'error-400',
    'text-warning-primary': 'warning-400',
    'text-success-primary': 'success-400',

    // Border tokens
    'border-primary': 'neutral-700',
    'border-secondary': 'neutral-800',
    'border-tertiary': 'neutral-800',
    'border-disabled': 'neutral-700',
    'border-disabled_subtle': 'neutral-800',
    'border-brand': 'brand-700',
    'border-brand-solid': 'brand-400',
    'border-brand-solid_alt': 'brand-400',
    'border-error': 'error-700',
    'border-error-solid': 'error-400',

    // Button tokens
    'button-secondary-fg': 'neutral-300',
    'button-secondary-fg_hover': 'neutral-200',
    'button-secondary-bg': 'neutral-950',
    'button-secondary-bg_hover': 'neutral-900',
    'button-secondary-bg_press': 'neutral-800',
    'button-secondary-border': 'neutral-700',
    'button-secondary-border_hover': 'neutral-700',

    // Foreground tokens
    'fg-primary': 'neutral-50',
    'fg-secondary': 'neutral-300',
    'fg-secondary_hover': 'neutral-200',
    'fg-tertiary': 'neutral-400',
    'fg-tertiary_hover': 'neutral-300',
    'fg-quaternary': 'neutral-400',
    'fg-quaternary_hover': 'neutral-300',
    'fg-quinary': 'neutral-500',
    'fg-quinary_hover': 'neutral-400',
    'fg-senary': 'neutral-600',
    'fg-white': 'base-white',
    'fg-disabled': 'neutral-500',
    'fg-disabled_subtle': 'neutral-600',
    'fg-brand-primary': 'brand-400',
    'fg-brand-primary_alt': 'brand-400',
    'fg-brand-secondary': 'brand-500',
    'fg-error-primary': 'error-400',
    'fg-error-secondary': 'error-500',
    'fg-warning-primary': 'warning-400',
    'fg-warning-secondary': 'warning-500',
    'fg-success-primary': 'success-400',
    'fg-success-secondary': 'success-500',

    // Background tokens
    'bg-primary': 'neutral-950',
    'bg-primary_alt': 'neutral-950',
    'bg-primary_hover': 'neutral-900',
    'bg-primary_press': 'neutral-800',
    'bg-secondary': 'neutral-900',
    'bg-secondary_alt': 'neutral-900',
    'bg-secondary_hover': 'neutral-800',
    'bg-secondary_press': 'neutral-700',
    'bg-secondary_subtle': 'neutral-950',
    'bg-secondary_solid': 'neutral-700',
    'bg-tertiary': 'neutral-800',
    'bg-quaternary': 'neutral-700',
    'bg-active': 'neutral-800',
    'bg-disabled': 'neutral-800',
    'bg-disabled_subtle': 'neutral-900',
    'bg-overlay': 'neutral-50',
    'bg-brand-primary': 'brand-900',
    'bg-brand-primary_alt': 'brand-900',
    'bg-brand-secondary': 'brand-800',
    'bg-brand-solid': 'brand-400',
    'bg-brand-solid_hover': 'brand-300',
    'bg-brand-solid_press': 'brand-200',
    'bg-brand-section': 'brand-200',
    'bg-brand-section_subtle': 'brand-300',
    'bg-error-primary': 'error-900',
    'bg-error-secondary': 'error-800',
    'bg-error-solid': 'error-400',
    'bg-warning-primary': 'warning-900',
    'bg-warning-secondary': 'warning-800',
    'bg-warning-solid': 'warning-400',
    'bg-success-primary': 'success-900',
    'bg-success-secondary': 'success-800',
    'bg-success-solid': 'success-400'
  }
} as const;

export type TokenMappingMode = keyof typeof TOKEN_MAPPINGS;
export type TokenKey = keyof typeof TOKEN_MAPPINGS.light;